export type ToolCategory = "dev" | "media" | "ai";
export type CostTier = "free" | "huggingface" | "claude";

export interface FAQ {
  question: string;
  answer: string;
}

export interface ToolDefinition {
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  category: ToolCategory;
  costTier: CostTier;
  keywords: string[];
  icon: string; // Lucide icon name
  isNew?: boolean;
  isPro?: boolean;
  relatedSlugs?: string[];
  faq?: FAQ[];
}

// Central registry — add a tool by adding an entry here + creating the component
export const tools: ToolDefinition[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter & Validator",
    description: "Format, validate, and beautify JSON with AI-powered error explanations.",
    longDescription: "Paste your JSON to instantly format, validate, and beautify it. Get clear error messages with AI-powered explanations when your JSON is invalid. Supports minification, tree view, and copy-to-clipboard.",
    category: "dev",
    costTier: "free",
    keywords: ["json formatter", "json validator", "json beautifier", "json formatter online", "format json"],
    icon: "Braces",
    relatedSlugs: ["csv-json", "jwt-decoder", "base64", "regex-tester"],
    faq: [
      { question: "What is JSON?", answer: "JSON (JavaScript Object Notation) is a lightweight data format used to exchange data between servers and web applications. It's human-readable and easy for machines to parse." },
      { question: "Why does my JSON fail validation?", answer: "Common issues include trailing commas after the last item in an array or object, single quotes instead of double quotes, unquoted keys, and missing commas between elements." },
      { question: "Is my data safe?", answer: "Yes. All formatting and validation happens entirely in your browser. Your JSON is never sent to any server." },
      { question: "Can I minify JSON here?", answer: "Yes. After formatting, use the minify option to remove all whitespace and produce compact JSON suitable for production use." },
    ],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate UUIDs (v4) instantly. Bulk generation, copy-to-clipboard.",
    longDescription: "Generate cryptographically secure UUIDs (Universally Unique Identifiers) version 4. Create single or bulk UUIDs, copy to clipboard, and choose your format. No data leaves your browser.",
    category: "dev",
    costTier: "free",
    keywords: ["uuid generator", "guid generator", "uuid v4", "random uuid", "unique id generator"],
    icon: "Fingerprint",
    relatedSlugs: ["hash-generator", "password-generator", "json-formatter"],
    faq: [
      { question: "What is a UUID?", answer: "A UUID (Universally Unique Identifier) is a 128-bit identifier that is guaranteed to be unique across space and time. The v4 variant uses random numbers, making collisions practically impossible." },
      { question: "What's the difference between UUID and GUID?", answer: "They're the same thing. UUID is the official standard name (RFC 4122), while GUID (Globally Unique Identifier) is Microsoft's term for the same concept." },
      { question: "Are UUIDs truly unique?", answer: "For practical purposes, yes. The probability of generating two identical v4 UUIDs is approximately 1 in 5.3 × 10^36. You'd need to generate 1 billion UUIDs per second for 85 years to have a 50% chance of a collision." },
    ],
  },
  {
    slug: "base64",
    name: "Base64 Encode / Decode",
    description: "Encode and decode Base64 strings instantly in your browser.",
    longDescription: "Convert text to Base64 and back instantly. Supports UTF-8, file encoding, URL-safe Base64, and handles large inputs efficiently. All processing happens client-side — your data never leaves your browser.",
    category: "dev",
    costTier: "free",
    keywords: ["base64 decode", "base64 encode", "base64 decoder", "base64 encoder", "base64 decode online"],
    icon: "Binary",
    relatedSlugs: ["url-encoder", "hash-generator", "jwt-decoder", "json-formatter"],
    faq: [
      { question: "What is Base64 encoding?", answer: "Base64 is a binary-to-text encoding scheme that converts binary data into ASCII characters. It's commonly used to embed images in HTML/CSS, encode email attachments, and transmit data in URLs or JSON." },
      { question: "Why is Base64 encoded data about 33% larger?", answer: "Base64 uses 6 bits per character instead of 8, so every 3 bytes of input become 4 bytes of output. This 4/3 ratio means the encoded data is always about 33% larger than the original." },
      { question: "Is Base64 encryption?", answer: "No. Base64 is an encoding, not encryption. Anyone can decode Base64 — it provides no security. Use it for safe data transport, not for hiding sensitive information." },
    ],
  },
  {
    slug: "regex-tester",
    name: "Regex Tester & AI Builder",
    description: "Test regex patterns with live matching. Describe what you need in plain English and AI builds the regex.",
    longDescription: "A powerful regular expression tester with real-time matching, group highlighting, and an AI-powered builder. Describe what you want to match in plain English and get a working regex instantly. Includes cheat sheet and common patterns.",
    category: "dev",
    costTier: "claude",
    keywords: ["regex tester", "regex tester online", "regular expression tester", "regex builder", "regex generator"],
    icon: "Regex",
    relatedSlugs: ["json-formatter", "diff-checker", "cron-generator"],
    faq: [
      { question: "What are regular expressions?", answer: "Regular expressions (regex) are patterns used to match character combinations in strings. They're essential for validation, search-and-replace, and data extraction in programming." },
      { question: "How does the AI regex builder work?", answer: "Describe what you want to match in plain English — like 'email addresses' or 'dates in MM/DD/YYYY format' — and AI generates a tested regex pattern with an explanation of each part." },
      { question: "Which regex flavors are supported?", answer: "The tester uses JavaScript's built-in regex engine, which supports most common features including lookahead, lookbehind, named groups, and Unicode properties." },
    ],
  },
  {
    slug: "background-remover",
    name: "Background Remover",
    description: "Remove image backgrounds instantly with AI. Free, no signup required.",
    longDescription: "Upload any image and get a clean transparent PNG with the background removed. Powered by AI segmentation models. Works with photos, product images, portraits, and more. No signup needed.",
    category: "media",
    costTier: "huggingface",
    keywords: ["remove background", "background remover", "remove background from image free", "transparent background", "bg remover"],
    icon: "ImageMinus",
    relatedSlugs: ["image-compressor", "ai-image-generator", "image-to-text"],
    faq: [
      { question: "How does the background remover work?", answer: "It uses an AI segmentation model that identifies the foreground subject and removes everything else. The result is a transparent PNG you can use anywhere." },
      { question: "What image formats are supported?", answer: "You can upload PNG, JPEG, and WebP images up to 10MB. The output is always a transparent PNG." },
      { question: "Is it really free?", answer: "Yes. The AI model runs on Hugging Face Spaces at no cost. No signup, no watermarks, no hidden fees." },
      { question: "Why does it take a while sometimes?", answer: "The AI model may need 30-60 seconds to 'warm up' if it hasn't been used recently. Subsequent uses are much faster." },
    ],
  },
  {
    slug: "image-to-text",
    name: "Image to Text (OCR)",
    description: "Extract text from images and screenshots using AI-powered OCR.",
    longDescription: "Upload an image, screenshot, or photo and extract all text content using advanced AI OCR. Supports multiple languages, handwriting recognition, and outputs clean Markdown. Perfect for digitizing documents, receipts, and screenshots.",
    category: "media",
    costTier: "huggingface",
    keywords: ["image to text", "ocr online", "image to text converter", "extract text from image", "screenshot to text"],
    icon: "ScanText",
    relatedSlugs: ["background-remover", "word-counter", "ai-image-generator"],
    faq: [
      { question: "What is OCR?", answer: "OCR (Optical Character Recognition) is a technology that reads text from images. Our AI-powered OCR goes beyond traditional methods — it understands layouts, tables, and even handwriting." },
      { question: "Can it read handwriting?", answer: "Yes. The AI model can recognize handwritten text, though accuracy depends on legibility. Printed text gives the best results." },
      { question: "What output format do I get?", answer: "The extracted text is returned as clean Markdown, preserving headings, lists, and table structures from the original image." },
    ],
  },
  {
    slug: "privacy-policy-generator",
    name: "Privacy Policy Generator",
    description: "Generate a professional privacy policy for your app or website using AI.",
    longDescription: "Describe your app or website and get a comprehensive, legally-informed privacy policy generated by AI. Covers GDPR, CCPA, cookies, data collection, third-party services, and more. Customizable and ready to publish.",
    category: "ai",
    costTier: "claude",
    keywords: ["privacy policy generator", "privacy policy generator free", "generate privacy policy", "privacy policy template"],
    icon: "Shield",
    relatedSlugs: ["word-counter", "lorem-ipsum", "regex-tester"],
    faq: [
      { question: "Is the generated privacy policy legally binding?", answer: "The AI generates a professionally worded policy based on best practices and common legal frameworks (GDPR, CCPA). However, you should have a lawyer review it before publishing for your specific jurisdiction." },
      { question: "What regulations does it cover?", answer: "The generated policy addresses GDPR (EU), CCPA (California), cookie consent, data collection practices, third-party services, children's privacy (COPPA), and data retention policies." },
      { question: "Can I customize the output?", answer: "Yes. The AI tailors the policy to your specific app or website based on what you describe — the technologies you use, data you collect, and services you integrate." },
    ],
  },
  {
    slug: "ai-image-generator",
    name: "AI Image Generator",
    description: "Generate images from text descriptions using AI. Free, no signup.",
    longDescription: "Describe what you want to see and AI generates it. Create illustrations, concept art, product mockups, and more. Powered by state-of-the-art diffusion models. Multiple styles and aspect ratios supported.",
    category: "media",
    costTier: "huggingface",
    keywords: ["ai image generator", "ai image generator free", "text to image", "ai art generator", "image generator"],
    icon: "Sparkles",
    relatedSlugs: ["background-remover", "image-compressor", "text-to-speech"],
    faq: [
      { question: "What AI model is used?", answer: "AllKit uses FLUX.1 Schnell, a fast diffusion model optimized for high-quality image generation. It generates 1024×1024 images in about 4 inference steps." },
      { question: "Can I use generated images commercially?", answer: "FLUX.1 Schnell is released under the Apache 2.0 license, which permits commercial use. However, always check the latest license terms for your specific use case." },
      { question: "How do I get better results?", answer: "Be specific in your prompts. Instead of 'a dog', try 'a golden retriever sitting in a sunlit meadow, professional photography, shallow depth of field'. Adding style cues and details improves output quality significantly." },
    ],
  },
  {
    slug: "cron-generator",
    name: "Cron Expression Generator",
    description: "Build and decode cron expressions visually. Describe your schedule in plain English and AI builds it.",
    longDescription: "Create cron expressions with an intuitive visual editor or describe your schedule in plain English and let AI generate the expression. See next run times, use common presets, and learn cron syntax with the built-in cheat sheet. Supports standard 5-field cron format.",
    category: "dev",
    costTier: "claude",
    keywords: ["cron expression generator", "crontab generator", "cron builder", "cron schedule", "crontab guru"],
    icon: "Clock",
    isNew: true,
    relatedSlugs: ["unix-timestamp", "regex-tester", "json-formatter"],
    faq: [
      { question: "What is a cron expression?", answer: "A cron expression is a string of 5 fields (minute, hour, day of month, month, day of week) that defines a schedule for running automated tasks. For example, '0 9 * * 1' means 'every Monday at 9:00 AM'." },
      { question: "How does the AI builder work?", answer: "Describe your schedule in plain English — like 'every weekday at 8am' or 'first Sunday of each month at midnight' — and AI generates the correct cron expression with an explanation." },
      { question: "What cron format is supported?", answer: "Standard 5-field cron format used by crontab on Linux/macOS, as well as most CI/CD platforms, cloud schedulers, and task runners." },
    ],
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, SHA-384, and SHA-512 hashes instantly.",
    longDescription: "Enter any text and instantly generate cryptographic hashes using MD5, SHA-1, SHA-256, SHA-384, and SHA-512 algorithms. All processing happens client-side using the Web Crypto API — your data never leaves your browser. Perfect for verifying file integrity, generating checksums, and security testing.",
    category: "dev",
    costTier: "free",
    keywords: ["hash generator", "md5 hash generator", "sha256 hash", "sha1 hash online", "hash generator online"],
    icon: "Hash",
    isNew: true,
    relatedSlugs: ["password-generator", "base64", "uuid-generator"],
    faq: [
      { question: "What is a hash?", answer: "A cryptographic hash is a fixed-size string generated from input data. The same input always produces the same hash, but you cannot reverse a hash back to the original data. Hashes are used for password storage, file integrity checks, and digital signatures." },
      { question: "Which hash algorithm should I use?", answer: "Use SHA-256 for most purposes — it's secure and widely supported. Avoid MD5 and SHA-1 for security-critical applications as they have known vulnerabilities. SHA-512 offers the highest security margin." },
      { question: "Is MD5 still safe to use?", answer: "MD5 is broken for security purposes — collisions can be generated in seconds. It's still fine for non-security uses like checksums or cache keys, but never use it for passwords or digital signatures." },
    ],
  },
  {
    slug: "color-palette",
    name: "Color Palette Generator",
    description: "Generate beautiful color palettes with harmony rules. Copy HEX, RGB, and HSL values.",
    longDescription: "Create stunning color palettes with one click. Generate random palettes, explore color harmonies (complementary, analogous, triadic, split-complementary), and lock colors you like. Copy values in HEX, RGB, or HSL format. Perfect for designers, developers, and anyone who works with color.",
    category: "dev",
    costTier: "free",
    keywords: ["color palette generator", "color scheme generator", "color palette", "color generator", "coolors alternative"],
    icon: "Palette",
    isNew: true,
    relatedSlugs: ["lorem-ipsum", "qr-code-generator", "json-formatter"],
    faq: [
      { question: "What are color harmonies?", answer: "Color harmonies are combinations of colors based on their positions on the color wheel. Complementary colors are opposite each other, analogous are adjacent, and triadic are evenly spaced. These rules help create visually pleasing palettes." },
      { question: "What's the difference between HEX, RGB, and HSL?", answer: "HEX (#FF5733) is a compact format used in CSS. RGB (255, 87, 51) defines colors by red, green, blue values. HSL (14°, 100%, 60%) uses hue, saturation, lightness — often more intuitive for picking colors." },
    ],
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text in paragraphs, sentences, or words. Classic lorem ipsum.",
    longDescription: "Generate lorem ipsum placeholder text quickly. Choose between paragraphs, sentences, or word count. Optionally start with the classic 'Lorem ipsum dolor sit amet...' opening. Copy to clipboard with one click. Ideal for mockups, wireframes, and prototyping.",
    category: "dev",
    costTier: "free",
    keywords: ["lorem ipsum generator", "lorem ipsum", "placeholder text generator", "dummy text generator", "lipsum"],
    icon: "Type",
    isNew: true,
    relatedSlugs: ["word-counter", "color-palette", "diff-checker"],
    faq: [
      { question: "What is Lorem Ipsum?", answer: "Lorem Ipsum is placeholder text used in design and publishing since the 1500s. It comes from a scrambled passage of Cicero's 'De Finibus Bonorum et Malorum' (45 BC). It's used because it has a natural letter distribution that resembles readable English." },
      { question: "Why use Lorem Ipsum instead of real text?", answer: "Placeholder text prevents reviewers from focusing on content instead of design. Lorem ipsum has no meaningful content, so it keeps attention on layout, typography, and visual hierarchy." },
    ],
  },
  {
    slug: "text-to-speech",
    name: "Text to Speech",
    description: "Convert text to natural-sounding speech using AI. Download as audio file.",
    longDescription: "Type or paste any text and convert it to realistic speech using AI. Powered by ChatterboxTTS for expressive, natural-sounding audio. Adjust expressiveness and temperature. Download the result as a WAV file. Free, no signup required.",
    category: "media",
    costTier: "huggingface",
    keywords: ["text to speech", "tts online", "text to speech online free", "ai voice generator", "text to audio"],
    icon: "Volume2",
    isNew: true,
    relatedSlugs: ["ai-image-generator", "word-counter", "image-to-text"],
    faq: [
      { question: "What AI model is used for TTS?", answer: "AllKit uses ChatterboxTTS by Resemble AI — a state-of-the-art model that produces natural, expressive speech with controllable tone and emotion." },
      { question: "What audio format is the output?", answer: "The generated speech is downloaded as a WAV file, which is a high-quality uncompressed audio format compatible with virtually all audio players and editors." },
      { question: "Can I adjust the voice style?", answer: "Yes. You can control expressiveness (how animated the speech sounds) and temperature (how creative/varied the pronunciation is). Lower values are more neutral, higher values more dramatic." },
    ],
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from URLs, text, or data. Download as PNG or SVG.",
    longDescription: "Create QR codes instantly from any text, URL, email, phone number, or WiFi credentials. Customize colors and size. Download as high-resolution PNG. All processing happens client-side — your data never leaves your browser.",
    category: "dev",
    costTier: "free",
    keywords: ["qr code generator", "qr code generator free", "create qr code", "qr code maker", "free qr code"],
    icon: "QrCode",
    isNew: true,
    relatedSlugs: ["url-encoder", "password-generator", "uuid-generator"],
    faq: [
      { question: "What can I put in a QR code?", answer: "URLs, plain text, email addresses, phone numbers, WiFi credentials, vCard contacts, and more. The QR standard can encode up to 4,296 alphanumeric characters." },
      { question: "What size should my QR code be?", answer: "For print, use at least 2×2 cm (0.8×0.8 inches) at 300 DPI. For screens, 200×200 pixels is usually sufficient. The more data encoded, the denser the pattern and the larger the QR code needs to be for reliable scanning." },
      { question: "Do QR codes expire?", answer: "Static QR codes (like the ones generated here) never expire — the data is encoded directly in the pattern. Dynamic QR codes that redirect through a URL service can expire if the service shuts down." },
    ],
  },
  {
    slug: "diff-checker",
    name: "Diff Checker",
    description: "Compare two texts side-by-side and see the differences highlighted.",
    longDescription: "Paste two texts and instantly see a side-by-side comparison with additions, deletions, and modifications highlighted. Perfect for comparing code, config files, or any text. Supports line-by-line and word-by-word diff modes. All processing happens client-side.",
    category: "dev",
    costTier: "free",
    keywords: ["diff checker", "diff checker online", "text compare", "code diff", "compare text online"],
    icon: "GitCompareArrows",
    isNew: true,
    relatedSlugs: ["json-formatter", "word-counter", "regex-tester"],
    faq: [
      { question: "What is a diff?", answer: "A diff shows the differences between two pieces of text. Lines that were added appear in green, removed lines in red, and unchanged lines stay neutral. It's the same concept used in Git version control." },
      { question: "Can I compare code files?", answer: "Yes. The diff checker works with any plain text — code, config files, prose, CSV data, or any text format. It supports both line-by-line and word-by-word comparison modes." },
    ],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate strong, secure passwords instantly. Customize length, characters, and complexity.",
    longDescription: "Create cryptographically secure passwords with full control over length, character types, and complexity. Generate multiple passwords at once, check entropy and strength ratings, and copy to clipboard. All generation happens client-side using the Web Crypto API — nothing is sent to any server.",
    category: "dev",
    costTier: "free",
    keywords: ["password generator", "random password generator", "strong password generator", "secure password generator", "password generator online"],
    icon: "KeyRound",
    isNew: true,
    relatedSlugs: ["hash-generator", "uuid-generator", "base64"],
    faq: [
      { question: "How long should my password be?", answer: "At least 16 characters for important accounts. Each additional character exponentially increases the time needed to crack it. A 20-character password with mixed character types is effectively unbreakable with current technology." },
      { question: "Are these passwords truly random?", answer: "Yes. We use the Web Crypto API (crypto.getRandomValues), which provides cryptographically secure random numbers. This is the same source of randomness used for TLS/SSL encryption." },
      { question: "Is it safe to generate passwords online?", answer: "Yes, because everything happens in your browser. No passwords are sent to any server, stored anywhere, or logged. You can verify this by disconnecting from the internet — the tool still works." },
    ],
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and paragraphs. Reading time estimates.",
    longDescription: "Paste or type any text to get instant word count, character count, sentence count, paragraph count, and reading/speaking time estimates. See keyword density, most frequent words, and average word length. Perfect for writers, students, and SEO professionals. All processing happens in your browser.",
    category: "dev",
    costTier: "free",
    keywords: ["word counter", "character counter", "word count online", "letter counter", "word counter online"],
    icon: "FileText",
    isNew: true,
    relatedSlugs: ["lorem-ipsum", "diff-checker", "csv-json"],
    faq: [
      { question: "How is reading time calculated?", answer: "Reading time is based on the average adult reading speed of 200-250 words per minute. Speaking time uses 130-150 words per minute. These are averages — technical content takes longer, familiar topics faster." },
      { question: "What is keyword density?", answer: "Keyword density is how often a word appears as a percentage of total words. SEO professionals use it to ensure natural keyword usage — generally 1-3% is recommended. Higher density may appear spammy to search engines." },
    ],
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description: "Compress and resize images in your browser. Supports JPEG, PNG, and WebP.",
    longDescription: "Upload images and compress them instantly without uploading to any server. Adjust quality, resize dimensions, and convert between JPEG, PNG, and WebP formats. See before/after file size comparison with percentage saved. Batch compress multiple images at once. 100% client-side — your images never leave your device.",
    category: "media",
    costTier: "free",
    keywords: ["image compressor", "compress image online", "image compressor online", "reduce image size", "compress jpg online"],
    icon: "ImageDown",
    isNew: true,
    relatedSlugs: ["background-remover", "ai-image-generator", "qr-code-generator"],
    faq: [
      { question: "Will compressing reduce image quality?", answer: "Slightly, but often imperceptibly. At 80% quality, JPEG images look virtually identical to the original while being 60-80% smaller. WebP format achieves even better compression at the same quality level." },
      { question: "Which format should I use?", answer: "WebP offers the best size-to-quality ratio and is supported by all modern browsers. Use JPEG for photos if you need maximum compatibility. Use PNG only when you need transparency." },
      { question: "Are my images uploaded anywhere?", answer: "No. All compression happens in your browser using the HTML5 Canvas API. Your images never leave your device — you can even use this tool offline." },
    ],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Tokens. View header, payload, and expiration status.",
    longDescription: "Paste any JWT token to instantly decode and inspect its header, payload, and signature. See human-readable claim explanations, expiration status, and validation warnings. Color-coded token parts make it easy to understand the structure. Like jwt.io but faster and cleaner. All decoding happens client-side.",
    category: "dev",
    costTier: "free",
    keywords: ["jwt decoder", "jwt decode", "jwt.io", "json web token decoder", "jwt token decoder"],
    icon: "ShieldCheck",
    isNew: true,
    relatedSlugs: ["json-formatter", "base64", "hash-generator"],
    faq: [
      { question: "What is a JWT?", answer: "A JSON Web Token (JWT) is a compact, URL-safe token format used for authentication and information exchange. It contains three parts: a header (algorithm info), payload (claims/data), and signature (verification)." },
      { question: "Is it safe to paste my JWT here?", answer: "Yes. Decoding happens entirely in your browser — the token is never sent to any server. However, note that JWTs are only encoded (Base64), not encrypted — anyone with the token can read its contents." },
      { question: "Can this tool verify JWT signatures?", answer: "This tool decodes and displays JWT contents but does not verify signatures, as that requires the secret key or public key used to sign the token. It will flag expired tokens and show all claims." },
    ],
  },
  {
    slug: "unix-timestamp",
    name: "Unix Timestamp Converter",
    description: "Convert Unix timestamps to human-readable dates and vice versa. Supports seconds and milliseconds.",
    longDescription: "Convert between Unix timestamps and human-readable dates instantly. Supports both seconds and milliseconds formats, with automatic detection. See results in local time, UTC, ISO 8601, and relative format. Includes current timestamp display and common timestamp references. All processing happens client-side.",
    category: "dev",
    costTier: "free",
    keywords: ["unix timestamp converter", "epoch converter", "timestamp to date", "unix time converter", "epoch to date"],
    icon: "Clock",
    isNew: true,
    relatedSlugs: ["cron-generator", "json-formatter", "uuid-generator"],
    faq: [
      { question: "What is a Unix timestamp?", answer: "A Unix timestamp (also called epoch time) is the number of seconds that have elapsed since January 1, 1970, 00:00:00 UTC. It's used universally in programming to represent dates and times as a single number." },
      { question: "What is the Year 2038 problem?", answer: "32-bit systems store Unix timestamps as signed 32-bit integers, which max out at 2,147,483,647 (January 19, 2038, 03:14:07 UTC). After this, the value overflows. Most modern systems use 64-bit timestamps, which last until the year 292 billion." },
      { question: "Seconds or milliseconds?", answer: "Unix timestamps in seconds have 10 digits (e.g., 1700000000). JavaScript and Java typically use milliseconds (13 digits, e.g., 1700000000000). This tool auto-detects the format." },
    ],
  },
  {
    slug: "url-encoder",
    name: "URL Encode / Decode",
    description: "Encode and decode URLs and query strings instantly. Supports encodeURIComponent and encodeURI.",
    longDescription: "Encode and decode URLs, query parameters, and special characters instantly. Choose between encodeURIComponent (encodes everything) and encodeURI (preserves URL structure). Includes a reference table of common URL encodings. All processing happens in your browser — no data is sent to any server.",
    category: "dev",
    costTier: "free",
    keywords: ["url encoder", "url decoder", "url encode online", "url decode online", "percent encoding"],
    icon: "Link",
    isNew: true,
    relatedSlugs: ["base64", "json-formatter", "qr-code-generator"],
    faq: [
      { question: "Why do URLs need encoding?", answer: "URLs can only contain a limited set of ASCII characters. Special characters like spaces, &, =, and non-ASCII characters must be percent-encoded (e.g., space becomes %20) to be safely transmitted in URLs." },
      { question: "What's the difference between encodeURI and encodeURIComponent?", answer: "encodeURI preserves URL-structural characters like :, /, ?, # — use it for complete URLs. encodeURIComponent encodes everything except letters and digits — use it for query parameter values." },
      { question: "What is percent encoding?", answer: "Percent encoding (also called URL encoding) replaces unsafe characters with a % followed by their hexadecimal ASCII value. For example, a space becomes %20, & becomes %26." },
    ],
  },
  {
    slug: "csv-json",
    name: "CSV to JSON Converter",
    description: "Convert CSV to JSON and JSON to CSV. Supports custom delimiters, file upload, and download.",
    longDescription: "Convert between CSV and JSON formats instantly. Supports comma, semicolon, tab, and pipe delimiters. Upload CSV or JSON files, or paste data directly. Download converted output as a file. Handles quoted fields, escaped characters, and large datasets. All processing happens client-side — your data never leaves your browser.",
    category: "dev",
    costTier: "free",
    keywords: ["csv to json", "json to csv", "csv to json converter", "convert csv to json online", "json to csv converter"],
    icon: "FileSpreadsheet",
    isNew: true,
    relatedSlugs: ["json-formatter", "diff-checker", "word-counter"],
    faq: [
      { question: "What delimiter should I use?", answer: "Comma is the standard for CSV files. Use semicolon if your data contains commas (common in European locales). Tab-separated is great for data copied from spreadsheets. Pipe is used in some legacy systems." },
      { question: "Can it handle quoted fields?", answer: "Yes. The parser correctly handles fields wrapped in double quotes, including fields that contain commas, newlines, or escaped quotes within the quoted value." },
      { question: "Is there a file size limit?", answer: "There's no hard limit since processing happens in your browser, but very large files (>50MB) may cause your browser to slow down. For typical CSV files (thousands of rows), it works instantly." },
    ],
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    description: "Write Markdown and see rendered HTML in real-time. Split, source, and preview modes.",
    longDescription: "A live Markdown editor with instant preview. Write Markdown on one side and see beautifully rendered HTML on the other. Supports headers, bold, italic, links, images, code blocks, lists, blockquotes, and more. Copy rendered HTML with one click. Split view, source-only, and preview-only modes. All processing happens client-side.",
    category: "dev",
    costTier: "free",
    keywords: ["markdown preview", "markdown editor online", "markdown to html", "markdown viewer", "markdown renderer"],
    icon: "FileCode",
    isNew: true,
    relatedSlugs: ["diff-checker", "word-counter", "lorem-ipsum", "json-formatter"],
    faq: [
      { question: "What is Markdown?", answer: "Markdown is a lightweight markup language for creating formatted text using plain text syntax. Created by John Gruber in 2004, it's widely used for documentation, README files, blog posts, and messaging. It's simpler than HTML but converts to HTML seamlessly." },
      { question: "What Markdown features are supported?", answer: "Headers (h1-h4), bold, italic, strikethrough, links, images, code blocks, inline code, ordered and unordered lists, blockquotes, horizontal rules, and more." },
      { question: "Can I copy the rendered HTML?", answer: "Yes. Click 'Copy HTML' to copy the generated HTML markup to your clipboard, ready to paste into any website or CMS." },
    ],
  },
  {
    slug: "yaml-json",
    name: "YAML to JSON Converter",
    description: "Convert YAML to JSON and JSON to YAML instantly. Bidirectional, no dependencies.",
    longDescription: "Convert between YAML and JSON formats in real-time. Paste YAML and get formatted JSON, or paste JSON and get clean YAML. Handles nested objects, arrays, strings, numbers, booleans, and null values. Swap between modes with one click. All conversion happens client-side — your data never leaves your browser.",
    category: "dev",
    costTier: "free",
    keywords: ["yaml to json", "json to yaml", "yaml to json converter", "convert yaml to json online", "yaml converter"],
    icon: "FileJson",
    isNew: true,
    relatedSlugs: ["json-formatter", "csv-json", "diff-checker"],
    faq: [
      { question: "What is YAML?", answer: "YAML (YAML Ain't Markup Language) is a human-readable data serialization format. It's commonly used for configuration files (Docker Compose, Kubernetes, GitHub Actions, CI/CD pipelines). Unlike JSON, YAML uses indentation instead of braces and supports comments." },
      { question: "When should I use YAML vs JSON?", answer: "Use YAML for configuration files that humans edit frequently — it's more readable and supports comments. Use JSON for data exchange between systems, API responses, and when you need strict parsing. JSON is a subset of YAML, so any valid JSON is also valid YAML." },
      { question: "Does it handle complex YAML?", answer: "It handles the most common YAML features: nested objects, arrays, strings, numbers, booleans, null, inline arrays, and comments. Advanced features like anchors, aliases, and multi-document streams are not yet supported." },
    ],
  },
  {
    slug: "html-entities",
    name: "HTML Entity Encoder / Decoder",
    description: "Encode and decode HTML entities. Convert special characters to their HTML entity equivalents.",
    longDescription: "Convert special characters like <, >, &, and quotes to their HTML entity equivalents and back. Supports named entities (&amp;, &lt;, &copy;), decimal entities (&#169;), and hexadecimal entities (&#xA9;). Includes a reference table of common HTML entities. Essential for web developers working with HTML content. All processing is client-side.",
    category: "dev",
    costTier: "free",
    keywords: ["html entity encoder", "html entity decoder", "html entities", "html encode online", "html special characters"],
    icon: "Code",
    isNew: true,
    relatedSlugs: ["url-encoder", "base64", "json-formatter"],
    faq: [
      { question: "What are HTML entities?", answer: "HTML entities are special codes used to represent characters that have special meaning in HTML. For example, < becomes &lt; because the browser would otherwise interpret it as the start of an HTML tag. They're also used for characters not on a standard keyboard, like © (&copy;) or € (&euro;)." },
      { question: "When do I need to encode HTML entities?", answer: "Whenever you display user-generated content in HTML, you must encode entities to prevent XSS (Cross-Site Scripting) attacks. Also when including special characters in HTML attributes, or when your content contains characters like <, >, &, or quotes." },
      { question: "What's the difference between named and numeric entities?", answer: "Named entities use readable names like &amp; or &copy;. Numeric entities use the character's Unicode code point: &#38; (decimal) or &#x26; (hex). Named entities are easier to read, but numeric entities can represent any Unicode character." },
    ],
  },
];

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): ToolDefinition[] {
  return tools.filter((t) => t.category === category);
}

export const categoryLabels: Record<ToolCategory, string> = {
  dev: "Developer Tools",
  media: "AI Media Tools",
  ai: "AI-Powered Tools",
};
