export type ToolCategory = "dev" | "media" | "ai";
export type CostTier = "free" | "huggingface" | "claude";

export interface ToolDefinition {
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  category: ToolCategory;
  costTier: CostTier;
  keywords: string[];
  icon: string; // Lucide icon name
  isNew?: boolean;
  isPro?: boolean;
}

// Central registry — add a tool by adding an entry here + creating the component
export const tools: ToolDefinition[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter & Validator",
    description: "Format, validate, and beautify JSON with AI-powered error explanations.",
    longDescription: "Paste your JSON to instantly format, validate, and beautify it. Get clear error messages with AI-powered explanations when your JSON is invalid. Supports minification, tree view, and copy-to-clipboard.",
    category: "dev",
    costTier: "free",
    keywords: ["json formatter", "json validator", "json beautifier", "json formatter online", "format json"],
    icon: "Braces",
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate UUIDs (v4) instantly. Bulk generation, copy-to-clipboard.",
    longDescription: "Generate cryptographically secure UUIDs (Universally Unique Identifiers) version 4. Create single or bulk UUIDs, copy to clipboard, and choose your format. No data leaves your browser.",
    category: "dev",
    costTier: "free",
    keywords: ["uuid generator", "guid generator", "uuid v4", "random uuid", "unique id generator"],
    icon: "Fingerprint",
  },
  {
    slug: "base64",
    name: "Base64 Encode / Decode",
    description: "Encode and decode Base64 strings instantly in your browser.",
    longDescription: "Convert text to Base64 and back instantly. Supports UTF-8, file encoding, URL-safe Base64, and handles large inputs efficiently. All processing happens client-side — your data never leaves your browser.",
    category: "dev",
    costTier: "free",
    keywords: ["base64 decode", "base64 encode", "base64 decoder", "base64 encoder", "base64 decode online"],
    icon: "Binary",
  },
  {
    slug: "regex-tester",
    name: "Regex Tester & AI Builder",
    description: "Test regex patterns with live matching. Describe what you need in plain English and AI builds the regex.",
    longDescription: "A powerful regular expression tester with real-time matching, group highlighting, and an AI-powered builder. Describe what you want to match in plain English and get a working regex instantly. Includes cheat sheet and common patterns.",
    category: "dev",
    costTier: "claude",
    keywords: ["regex tester", "regex tester online", "regular expression tester", "regex builder", "regex generator"],
    icon: "Regex",
  },
  {
    slug: "background-remover",
    name: "Background Remover",
    description: "Remove image backgrounds instantly with AI. Free, no signup required.",
    longDescription: "Upload any image and get a clean transparent PNG with the background removed. Powered by AI segmentation models. Works with photos, product images, portraits, and more. No signup needed.",
    category: "media",
    costTier: "huggingface",
    keywords: ["remove background", "background remover", "remove background from image free", "transparent background", "bg remover"],
    icon: "ImageMinus",
  },
  {
    slug: "image-to-text",
    name: "Image to Text (OCR)",
    description: "Extract text from images and screenshots using AI-powered OCR.",
    longDescription: "Upload an image, screenshot, or photo and extract all text content using advanced AI OCR. Supports multiple languages, handwriting recognition, and outputs clean Markdown. Perfect for digitizing documents, receipts, and screenshots.",
    category: "media",
    costTier: "huggingface",
    keywords: ["image to text", "ocr online", "image to text converter", "extract text from image", "screenshot to text"],
    icon: "ScanText",
  },
  {
    slug: "privacy-policy-generator",
    name: "Privacy Policy Generator",
    description: "Generate a professional privacy policy for your app or website using AI.",
    longDescription: "Describe your app or website and get a comprehensive, legally-informed privacy policy generated by AI. Covers GDPR, CCPA, cookies, data collection, third-party services, and more. Customizable and ready to publish.",
    category: "ai",
    costTier: "claude",
    keywords: ["privacy policy generator", "privacy policy generator free", "generate privacy policy", "privacy policy template"],
    icon: "Shield",
  },
  {
    slug: "ai-image-generator",
    name: "AI Image Generator",
    description: "Generate images from text descriptions using AI. Free, no signup.",
    longDescription: "Describe what you want to see and AI generates it. Create illustrations, concept art, product mockups, and more. Powered by state-of-the-art diffusion models. Multiple styles and aspect ratios supported.",
    category: "media",
    costTier: "huggingface",
    keywords: ["ai image generator", "ai image generator free", "text to image", "ai art generator", "image generator"],
    icon: "Sparkles",
  },
];

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): ToolDefinition[] {
  return tools.filter((t) => t.category === category);
}

export const categoryLabels: Record<ToolCategory, string> = {
  dev: "Developer Tools",
  media: "AI Media Tools",
  ai: "AI-Powered Tools",
};
